### ISSUE TITLE
[BUG] All application windows are showing even though i started search filter from within a single applications window

### ISSUE THREAD

**Issue by mlncn** [G-dH/advanced-alttab-window-switcher#125]
**Describe the bug**
Seems to have stopped allowing me to filter only one application's window for matches by text.

**To Reproduce**

1. Launch the switcher (Super+Tab for me)
2. Keep tabbing to an application with multiple windows
3. Start switching through the windows in that application (still holding down Super plus ``/~` for me)
4. Type some letters to filter these windows
5. See windows from all applications matching the filtered letters instead of only the windows that you were trying to filter

**Expected behavior**

When filtering within a single application's windows, only those windows are shown.

**Desktop (please complete the following information):**
 - OS: Debian testing
 - Version 47.0
 - extension.gnome.org

**Additional context**

The switcher is configured to group windows by application.

This had been working as expected.

Could not find any way to configure it to return to working as expected.

AATWS is what keeps me with Gnome!  Thank you for its amazingness.

**Comment by G-dH** [comment]
Thanks! I'll fix this.

**Comment by G-dH** [comment]
Fixed.

**Comment by mlncn** [comment]
I am still getting this behavior in 47.1, where starting to filter breaks me out of single application context and shows all open windows.  Would the fix be in this version already or should i be waiting?

**Comment by G-dH** [comment]
I'll update the e.g.o version soon. In the meantime, you can install the fixed AATWS from this repository and let me know how it works for you.

**Comment by G-dH** [comment]
The fixed version is already available on e.g.o.
