### ISSUE TITLE
Switch windows as Setup+J/K

### ISSUE THREAD

**Issue by hron** [G-dH/advanced-alttab-window-switcher#29]
I have the following overrides:

- `/org/gnome/desktop/wm/keybindings/switch-windows`: `<Super>j`
- `/org/gnome/desktop/wm/keybindings/switch-windows-backward`: `<Super>k`

It seems the extension ignores the keys. Super+j works and the switcher is showed, but I cannot witch forward using Super+j as I used to. Super+k is ignored completely. 

Is it possible to setup setup the extensions so Super+j/k will be the keybindings to switch between windows?

**Comment by G-dH** [comment]
There was an issue with the backward switching, should be fixed now in the repository. Note that your shortcuts interfere with the option _Search Mode as Default_, it needs to be disabled.

**Comment by hron** [comment]
Thanks! Now it works better, but still not exactly how I want ;] When I press Super+j the windows switcher is shown and can navigate back and forth using Super+j/k, but when I release Super key the switcher is still active. I expect it to select the window and go away, just like the default Gnome windows switcher.  Do I miss something again from the configuration?

**Comment by G-dH** [comment]
It definitely should activate the window when you release the shortcut's modifier keys (Super in your case) and it works this way for me. Try to open terminal, execute:
`journalctl /usr/bin/gnome-shell -fo cat`
and see if there is an error when you use the switcher.

**Comment by G-dH** [comment]
Show me your settings:

    gsettings --schemadir ~/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/schemas/ list-recursively  org.gnome.shell.extensions.advanced-alt-tab-window-switcher

**Comment by hron** [comment]
Sure thing!

```
➜ gsettings --schemadir ~/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/schemas/ list-recursively  org.gnome.shell.extensions.advanced-alt-tab-window-switcher
org.gnome.shell.extensions.advanced-alt-tab-window-switcher app-switcher-popup-fav-apps true
org.gnome.shell.extensions.advanced-alt-tab-window-switcher app-switcher-popup-fav-mru true
org.gnome.shell.extensions.advanced-alt-tab-window-switcher app-switcher-popup-filter 1
org.gnome.shell.extensions.advanced-alt-tab-window-switcher app-switcher-popup-hide-win-counter-for-single-window false
org.gnome.shell.extensions.advanced-alt-tab-window-switcher app-switcher-popup-icon-size 72
org.gnome.shell.extensions.advanced-alt-tab-window-switcher app-switcher-popup-mid-click-item 14
org.gnome.shell.extensions.advanced-alt-tab-window-switcher app-switcher-popup-prim-click-item 2
org.gnome.shell.extensions.advanced-alt-tab-window-switcher app-switcher-popup-raise-first-only false
org.gnome.shell.extensions.advanced-alt-tab-window-switcher app-switcher-popup-results-limit 12
org.gnome.shell.extensions.advanced-alt-tab-window-switcher app-switcher-popup-scroll-item 3
org.gnome.shell.extensions.advanced-alt-tab-window-switcher app-switcher-popup-search-pref-running false
org.gnome.shell.extensions.advanced-alt-tab-window-switcher app-switcher-popup-sec-click-item 9
org.gnome.shell.extensions.advanced-alt-tab-window-switcher app-switcher-popup-sorting 1
org.gnome.shell.extensions.advanced-alt-tab-window-switcher app-switcher-popup-titles true
org.gnome.shell.extensions.advanced-alt-tab-window-switcher app-switcher-popup-win-counter true
org.gnome.shell.extensions.advanced-alt-tab-window-switcher enable-super false
org.gnome.shell.extensions.advanced-alt-tab-window-switcher hotkey-above 'A'
org.gnome.shell.extensions.advanced-alt-tab-window-switcher hotkey-close-all-app 'C'
org.gnome.shell.extensions.advanced-alt-tab-window-switcher hotkey-close-quit 'W'
org.gnome.shell.extensions.advanced-alt-tab-window-switcher hotkey-down 'J'
org.gnome.shell.extensions.advanced-alt-tab-window-switcher hotkey-fs-on-new-ws 'F'
org.gnome.shell.extensions.advanced-alt-tab-window-switcher hotkey-group-ws 'G'
org.gnome.shell.extensions.advanced-alt-tab-window-switcher hotkey-left 'H'
org.gnome.shell.extensions.advanced-alt-tab-window-switcher hotkey-maximize 'M'
org.gnome.shell.extensions.advanced-alt-tab-window-switcher hotkey-move-win-to-monitor 'X'
org.gnome.shell.extensions.advanced-alt-tab-window-switcher hotkey-new-win 'N'
org.gnome.shell.extensions.advanced-alt-tab-window-switcher hotkey-prefs 'P'
org.gnome.shell.extensions.advanced-alt-tab-window-switcher hotkey-right 'L'
org.gnome.shell.extensions.advanced-alt-tab-window-switcher hotkey-search 'E'
org.gnome.shell.extensions.advanced-alt-tab-window-switcher hotkey-single-app '1+'
org.gnome.shell.extensions.advanced-alt-tab-window-switcher hotkey-sticky 'S'
org.gnome.shell.extensions.advanced-alt-tab-window-switcher hotkey-switch-filter 'Q'
org.gnome.shell.extensions.advanced-alt-tab-window-switcher hotkey-switcher-mode 'F'
org.gnome.shell.extensions.advanced-alt-tab-window-switcher hotkey-thumbnail 'T'
org.gnome.shell.extensions.advanced-alt-tab-window-switcher hotkey-up 'K'
org.gnome.shell.extensions.advanced-alt-tab-window-switcher super-double-press-action 1
org.gnome.shell.extensions.advanced-alt-tab-window-switcher super-key-mode 1
org.gnome.shell.extensions.advanced-alt-tab-window-switcher switcher-popup-activate-on-hide false
org.gnome.shell.extensions.advanced-alt-tab-window-switcher switcher-popup-ext-app-stable true
org.gnome.shell.extensions.advanced-alt-tab-window-switcher switcher-popup-hot-keys false
org.gnome.shell.extensions.advanced-alt-tab-window-switcher switcher-popup-hover-select true
org.gnome.shell.extensions.advanced-alt-tab-window-switcher switcher-popup-mid-click-in 99
org.gnome.shell.extensions.advanced-alt-tab-window-switcher switcher-popup-mid-click-out 12
org.gnome.shell.extensions.advanced-alt-tab-window-switcher switcher-popup-monitor 1
org.gnome.shell.extensions.advanced-alt-tab-window-switcher switcher-popup-pointer true
org.gnome.shell.extensions.advanced-alt-tab-window-switcher switcher-popup-pointer-timeout 1200
org.gnome.shell.extensions.advanced-alt-tab-window-switcher switcher-popup-position 2
org.gnome.shell.extensions.advanced-alt-tab-window-switcher switcher-popup-preview-selected 2
org.gnome.shell.extensions.advanced-alt-tab-window-switcher switcher-popup-prim-click-in 4
org.gnome.shell.extensions.advanced-alt-tab-window-switcher switcher-popup-prim-click-out 13
org.gnome.shell.extensions.advanced-alt-tab-window-switcher switcher-popup-reverse-auto false
org.gnome.shell.extensions.advanced-alt-tab-window-switcher switcher-popup-scroll-in 6
org.gnome.shell.extensions.advanced-alt-tab-window-switcher switcher-popup-scroll-out 13
org.gnome.shell.extensions.advanced-alt-tab-window-switcher switcher-popup-sec-click-in 17
org.gnome.shell.extensions.advanced-alt-tab-window-switcher switcher-popup-sec-click-out 11
org.gnome.shell.extensions.advanced-alt-tab-window-switcher switcher-popup-shift-hotkeys false
org.gnome.shell.extensions.advanced-alt-tab-window-switcher switcher-popup-start-search false
org.gnome.shell.extensions.advanced-alt-tab-window-switcher switcher-popup-status true
org.gnome.shell.extensions.advanced-alt-tab-window-switcher switcher-popup-sync-filter true
org.gnome.shell.extensions.advanced-alt-tab-window-switcher switcher-popup-timeout 100
org.gnome.shell.extensions.advanced-alt-tab-window-switcher switcher-popup-tooltip-label-scale 300
org.gnome.shell.extensions.advanced-alt-tab-window-switcher switcher-popup-tooltip-title 2
org.gnome.shell.extensions.advanced-alt-tab-window-switcher switcher-popup-up-down-action 1
org.gnome.shell.extensions.advanced-alt-tab-window-switcher switcher-popup-wrap true
org.gnome.shell.extensions.advanced-alt-tab-window-switcher win-switch-include-modals false
org.gnome.shell.extensions.advanced-alt-tab-window-switcher win-switch-mark-minimized true
org.gnome.shell.extensions.advanced-alt-tab-window-switcher win-switch-minimized-to-end true
org.gnome.shell.extensions.advanced-alt-tab-window-switcher win-switch-skip-minimized false
org.gnome.shell.extensions.advanced-alt-tab-window-switcher win-switcher-popup-filter 2
org.gnome.shell.extensions.advanced-alt-tab-window-switcher win-switcher-popup-icon-size 64
org.gnome.shell.extensions.advanced-alt-tab-window-switcher win-switcher-popup-mid-click-item 14
org.gnome.shell.extensions.advanced-alt-tab-window-switcher win-switcher-popup-order 1
org.gnome.shell.extensions.advanced-alt-tab-window-switcher win-switcher-popup-preview-size 256
org.gnome.shell.extensions.advanced-alt-tab-window-switcher win-switcher-popup-prim-click-item 2
org.gnome.shell.extensions.advanced-alt-tab-window-switcher win-switcher-popup-scroll-item 3
org.gnome.shell.extensions.advanced-alt-tab-window-switcher win-switcher-popup-search-all false
org.gnome.shell.extensions.advanced-alt-tab-window-switcher win-switcher-popup-search-apps false
org.gnome.shell.extensions.advanced-alt-tab-window-switcher win-switcher-popup-sec-click-item 10
org.gnome.shell.extensions.advanced-alt-tab-window-switcher win-switcher-popup-sorting 1
org.gnome.shell.extensions.advanced-alt-tab-window-switcher win-switcher-popup-titles 1
org.gnome.shell.extensions.advanced-alt-tab-window-switcher win-switcher-popup-ws-indexes false
org.gnome.shell.extensions.advanced-alt-tab-window-switcher win-switcher-single-prev-size 256
org.gnome.shell.extensions.advanced-alt-tab-window-switcher win-thumbnail-scale 15
org.gnome.shell.extensions.advanced-alt-tab-window-switcher wm-always-activate-focused false
org.gnome.shell.extensions.advanced-alt-tab-window-switcher ws-switch-ignore-last false
org.gnome.shell.extensions.advanced-alt-tab-window-switcher ws-switch-indicator-mode 4
org.gnome.shell.extensions.advanced-alt-tab-window-switcher ws-switch-popup true
org.gnome.shell.extensions.advanced-alt-tab-window-switcher ws-switch-wrap false
```

**Comment by hron** [comment]
I have tried to disable all the extensions except AATWS with restarting the shell, but it didn't help. 

Also I thought my setting for `/org/gnome/mutter/overlay-key` might be related. I use an empty string for this setting. I have tried  to set it to `Super_L` and `Super_R`, but the results are the same ;(

I use Ubuntu 22.04 LTS with gnome-shell 42.1-0ubuntu0.1.

**Comment by G-dH** [comment]
Ubuntu 22.04 is a distro on which I'm currently developing the AATWS. I'm unable to reproduce your issue on any of my test distros. The `overlay-key` setting has nothing to do with this. Only if you used the `overlay-key` to activate the AATWS switcher, releasing the key wouldn't close the switcher.

Are you experiencing the issue even when using the default shortcuts?
