### ISSUE TITLE
GNOME 45 support

### ISSUE THREAD

**Issue by G-dH** [G-dH/advanced-alttab-window-switcher#76]
Bug reports appreciated!

Installation of the development version:

    git clone https://github.com/G-dH/advanced-alttab-window-switcher.git
    cd advanced-alttab-window-switcher/

    make install

**Comment by johnl** [comment]
A build of that branch is working nicely for me so far with Gnome 45. Much appreciated @G-dH !

**Comment by G-dH** [comment]
@johnl Thank you for the feedback!

**Comment by TheTakylo** [comment]
I tried, no problem for all my uses.
thank you very much for this great extension!

**Comment by chsjr1996** [comment]
I tried too, no problem here! Thank you very much, I love this extension <3

**Comment by CheariX** [comment]
I have found two issues. I tested them with AATWS as the only active extension.

1) I can only see the the apps of the current monitor in the app switcher (Filter: ALL).

The workspace filter (WS) works as intended.

If I set the filter to MON, i can only thee apps on the current monitor AND current workspace (not sure if it should show apps from all workspaces).

2) Super (Windows) Key action is not working. Whether I set it to window switcher or to app swichter, pressing the super key always opens the overview.

**Comment by G-dH** [comment]
@CheariX Thanks, I forgot `.bind(this)` in connection callbacks and settings couldn't be updated on the fly. Should be fixed now.

**Comment by CheariX** [comment]
I can confirm that the (2) the super key action is now working a expected.

The app switcher (1) still shows apps only from the current monitor. The window switcher can show windows from all monitors.

**Comment by G-dH** [comment]
@CheariX: I can't reproduce your issue, all filters works as expected. Does the hotkey for switching window filter (Q / Shift + Q by default) works? Can you see anything relevant to AATWS in the log?

**Comment by CheariX** [comment]
Sorry for the late answer.
I've still the issue with the app switcher.

> Does the hotkey for switching app/window filter (Q / Shift + Q by default) work? 

It works as expected in the window switcher.
In the app switcher, it only toggles between showing the current WS and all WS apps. If it is set to `ALL`, it shows the same apps as on `MON`.

> Can you see anything relevant to AATWS in the log?

Where would  I find these logs?
I went to `lg` -> "Extensions" -> "AATWS" -> "Errors", but there is nothing.

**Comment by G-dH** [comment]
@CheariX 

> I did a reset of all AATWS settings. Now it is working as expected. Thank you for this great extension!

It would be nice to find out which option conflicts with the filter.
